# Generated by Django 5.2.7 on 2025-10-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tareas_prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba', models.TextField(max_length=200)),
                ('numero_prueba', models.IntegerField(verbose_name=20)),
            ],
        ),
    ]
